# Generated by Django 2.2.13 on 2020-06-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='syndrom',
        ),
    ]
